### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by odolbeau**

### CODE REVIEW

**Comment by EldarAliiev** [comment]
Already fixed, thanks.

**Comment by odolbeau** [comment]
That's a really strange way of dealing with PR! :thinking:

**Comment by lyrixx** [comment]
@odolbeau I let a comment on the commit 7ffcb01cd61a4fb577098e814686866fbc3dbb5a
But :joy: They deleted it :) But Github let the "reference" in this PR juste above : 
> lyrixx referenced this pull request 23 hours ago

**Comment by jeremyFreeAgent** [comment]
That is for his vanity metrics🥇

**Pull request closed without merging**
